name: fablab-service

services:
  fablab-api:
    build: .
    container_name: fablab-api
    restart: unless-stopped
    expose:
      - 8080
    env_file:
      - ./.env
    volumes:
      - ./uploads:/app/uploads
    networks:
      - fablab-service-network

networks:
  fablab-service-network:
    name: fablab-service-network
    driver: bridge